class player extends partisan{
    constructor(layer,x,y){
        super(layer,x,y,0,0,30,30)
        this.offset={position:{x:0,y:0}}
        this.anim={direction:0,rate:0}
        this.movement={speed:0.2,jump:12}
        this.base.movement={jump:this.movement.jump}
        this.reload=0
        this.jumps=0
        this.jumped=false
    }
    display(){
        if(this.fade>0&&this.size>0){
            this.layer.translate(this.position.x+this.offset.position.x,this.position.y+this.offset.position.y)
            this.layer.noStroke()
            this.layer.fill(175,this.fade)
            this.layer.rect(0,0,this.width,this.height)
            this.layer.fill(50,this.fade)
            for(let a=0;a<this.jumps;a++){
                this.layer.ellipse(this.width*0.75,-this.height*0.5-a*6,4,4)
            }
            this.layer.translate(-this.position.x-this.offset.position.x,-this.position.y-this.offset.position.y)
        }
    }
    update(){
        if(this.dead&&this.fade<=0){
            transition.trigger=true
            transition.scene='level'
        }
        if(inputs.keys[0][0]||inputs.keys[1][0]){
            this.velocity.x-=this.movement.speed
            if(this.anim.direction>-1){
                this.anim.direction-=0.1
            }
        }
        if(inputs.keys[0][1]||inputs.keys[1][1]){
            this.velocity.x+=this.movement.speed
            if(this.anim.direction<1){
                this.anim.direction+=0.1
            }
        }
        if(this.position.y<=0&&game.zone==levels.length-1){
            transition.trigger=true
            transition.scene='end'
        }
        if(this.position.x>=game.edge.x&&game.zone<levels.length-1&&!this.dead){
            transition.trigger=true
            transition.zone=game.zone+1
            transition.key=0
        }else if(this.position.x<=0&&game.zone>0&&!this.dead){
            transition.trigger=true
            transition.zone=game.zone-1
            transition.key=1
        }
        if(!inputs.keys[0][0]&&!inputs.keys[1][0]&&!inputs.keys[0][1]&&!inputs.keys[1][1]){
            this.anim.direction*=0.95
        }
        if((inputs.keys[0][2]||inputs.keys[1][2])&&(this.timers[0]>0||this.jumps>0&&!this.jumped)){
            if(this.timers[0]>0){
                this.timers[0]=0
            }else{
                this.jumps--
            }
            this.jumped=true
            this.velocity.y=-this.movement.jump
            this.timers[1]=1
        }
        this.movement.jump=this.base.movement.jump
        stage.focus.x=this.position.x
        stage.focus.y=this.position.y
        super.update()
    }
}